image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (запоминаем информацию о процессе в переменной $App)
  - java -jar ./artifacts/app-ibank-build-for-testers.jar &

build_script:
  - chmod +x gradlew
  - ./gradlew test --info -Dselenide.headless=true

